import { Column } from 'components/MUIComponent/Table/interfaces';

export const headData: Column[] = [
  { id: 'status', label: '' },
  {
    id: 'project',
    label: 'Project',
  },
  {
    id: 'environment',
    label: 'Environment',
  },
  { id: 'branch', label: 'Branch' },
  {
    id: 'commit',
    label: 'Commit',
  },
  { id: 'quality', label: 'Code Quality' },
  {
    id: 'build',
    label: 'Build',
  },
  {
    id: 'updated',
    label: 'Updated',
  },
  { id: 'updatedBy', label: 'Updated by' },
  { id: 'jobLog', label: 'Job log', canSort: true },
];

export const mockData = [
  {
    id: '1',
    status: 'status1',
    project: 'project1',
    environment: 'environment1',
    branch: 'branch1',
    commit: 'commit1',
    quality: 'quality1',
    build: 'build2',
    updated: 'updated1',
    updatedBy: 'updatedBy1',
    jobLog: 'jobLog1',
  },
  {
    id: '2',
    status: 'status2',
    project: 'project2',
    environment: 'environment2',
    branch: 'branch2',
    commit: 'commit2',
    quality: 'quality2',
    build: 'build2',
    updated: 'updated2',
    updatedBy: 'updatedBy2',
    jobLog: 'jobLog2',
  },
  {
    id: '3',
    status: 'status2',
    project: 'project2',
    environment: 'environment2',
    build: 'build2',
    branch: 'branch2',
    commit: 'commit2',
    quality: 'quality2',
    updated: 'updated2',
    updatedBy: 'updatedBy2',
    jobLog: 'jobLog2',
  },
  {
    id: '4',
    status: 'status4',
    project: 'project4',
    environment: 'environment4',
    build: 'build4',
    branch: 'branch4',
    commit: 'commit4',
    quality: 'quality4',
    updated: 'updated4',
    updatedBy: 'updatedBy4',
    jobLog: 'jobLog4',
  },
  {
    id: '5',
    status: 'status5',
    project: 'project5',
    environment: 'environment5',
    build: 'build5',
    branch: 'branch5',
    commit: 'commit5',
    quality: 'quality5',
    updated: 'updated5',
    updatedBy: 'updatedBy5',
    jobLog: 'jobLog5',
  },
  {
    id: '6',
    status: 'status6',
    project: 'project6',
    environment: 'environment6',
    build: 'build6',
    branch: 'branch6',
    commit: 'commit6',
    quality: 'quality6',
    updated: 'updated6',
    updatedBy: 'updatedBy6',
    jobLog: 'jobLog6',
  },
  {
    id: '7',
    status: 'status7',
    project: 'project7',
    environment: 'environment7',
    build: 'build7',
    branch: 'branch7',
    commit: 'commit7',
    quality: 'quality7',
    updated: 'updated7',
    updatedBy: 'updatedBy7',
    jobLog: 'jobLog7',
  },
  {
    id: '8',
    status: 'status8',
    project: 'project8',
    environment: 'environment8',
    build: 'build8',
    branch: 'branch8',
    commit: 'commit7',
    quality: 'quality7',
    updated: 'updated7',
    updatedBy: 'updatedBy7',
    jobLog: 'jobLog7',
  },
];
